---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "net-tools"]
    state: latest
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Disable IPv6 with sysctl
  become: true
  sysctl: name={{ item }} value=1 state=present reload=yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: "copy backend files"
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

#- name: "unzip folder."
#  become: true
#  unarchive:
#    src: /tmp/backend.zip
#    dest: /home/ubuntu
#    remote_src: yes

- name: Install, Build
  shell: |
    cd /home/ubuntu/backend
    npm install -g n
    sudo npm install -g n
    sudo npm install
    sudo npm run build

#- name: Start
#  shell: |
#    pm2 delete all
#    cd /home/ubuntu/backend
#    sudo pm2 start npm --name backend -- start

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/backend/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.[.ts,.js]"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
