---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy backend files"
  become: true
  synchronize:
    src: /root/project/backend.zip
    dest: /home/ubuntu/

#- name: "unzip folder."
#  become: true
#  unarchive:
#    src: /home/ubuntu/backend.zip
#    dest: /home/ubuntu
#    remote_src: yes

- name: "unzip folder."
  become: true
  shell: |
    unzip /home/ubuntu/backend.zip
    

- name: Disable IPv6 with sysctl
  become: true
  sysctl: name={{ item }} value=1 state=present reload=yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install and Build
  become: true
  shell: |
    pm2 delete all
    cd /home/ubuntu/backend
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    npm install -g n
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 start npm --name backend -- start

  
#- name: "start server"
#  shell: |
#   cd /home/ubuntu/backend
#    pm2 start npm --name backend -- run start