---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

#- name: "Copy Backend Files"
#  become: true
#  copy:
##    src: /~/cicdproject/backend.zip
#    dest: /home/ubuntu
#    remote_src: no

- name: "copy backend binaries"
  copy:
    src: /root/project/backend.zip
    dest: /home/ubuntu/
    

- name: "unzip folder."
  unarchive:
    src: /home/ubuntu/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: Install and Build
  shell: |
    cd /home/ubuntu/backend
    ls
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
  
- name: "start server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start